# Site Settings
title: Voidsec
email: octane007@proton.me
description: >- # this means to ignore newlines until "baseurl"
  Voidsec.
baseurl: "/voidsec" # the subpath of your site, e.g. /blog
url: "https://octane-sec.github.io/" # the base hostname & protocol for your site, e.g. http://localhost:4000

# Theme Settings
# Replace 'pages-themes/cayman' with any GitHub theme you like
remote_theme: pages-themes/cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Build Settings
exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
